services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install playwright
      playwright install
    startCommand: python main.py
